version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    pre_build:
      commands:
        - echo Build started
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - node initialize.js
      - echo Build completed on `date`
